/*
 * Rudra GNOME Extension
 * Copyright (C) 2026 NarkAgni
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

import Gio from 'gi://Gio';


const ICON_CATALOG = [
    { name: 'bookmark-new-symbolic',                               category: 'Actions' },
    { name: 'call-incoming-symbolic',                              category: 'Actions' },
    { name: 'call-missed-symbolic',                                category: 'Actions' },
    { name: 'call-outgoing-symbolic',                              category: 'Actions' },
    { name: 'call-start-symbolic',                                 category: 'Actions' },
    { name: 'call-stop-symbolic',                                  category: 'Actions' },
    { name: 'document-edit-symbolic',                              category: 'Actions' },
    { name: 'document-new-symbolic',                               category: 'Actions' },
    { name: 'document-open-recent-symbolic',                       category: 'Actions' },
    { name: 'document-open-symbolic',                              category: 'Actions' },
    { name: 'document-page-setup-symbolic',                        category: 'Actions' },
    { name: 'document-print-preview-symbolic',                     category: 'Actions' },
    { name: 'document-print-symbolic',                             category: 'Actions' },
    { name: 'document-properties-symbolic',                        category: 'Actions' },
    { name: 'document-revert-rtl-symbolic',                        category: 'Actions' },
    { name: 'document-revert-symbolic',                            category: 'Actions' },
    { name: 'document-save-as-symbolic',                           category: 'Actions' },
    { name: 'document-save-symbolic',                              category: 'Actions' },
    { name: 'document-send-symbolic',                              category: 'Actions' },
    { name: 'edit-clear-all-symbolic',                             category: 'Actions' },
    { name: 'edit-clear-rtl-symbolic',                             category: 'Actions' },
    { name: 'edit-clear-symbolic',                                 category: 'Actions' },
    { name: 'edit-copy-symbolic',                                  category: 'Actions' },
    { name: 'edit-cut-symbolic',                                   category: 'Actions' },
    { name: 'edit-delete-symbolic',                                category: 'Actions' },
    { name: 'edit-find-replace-symbolic',                          category: 'Actions' },
    { name: 'edit-find-symbolic',                                  category: 'Actions' },
    { name: 'edit-paste-symbolic',                                 category: 'Actions' },
    { name: 'edit-redo-symbolic',                                  category: 'Actions' },
    { name: 'edit-select-all-symbolic',                            category: 'Actions' },
    { name: 'edit-select-symbolic',                                category: 'Actions' },
    { name: 'edit-undo-symbolic',                                  category: 'Actions' },
    { name: 'go-bottom-symbolic',                                  category: 'Actions' },
    { name: 'go-down-symbolic',                                    category: 'Actions' },
    { name: 'go-first-symbolic',                                   category: 'Actions' },
    { name: 'go-home-symbolic',                                    category: 'Actions' },
    { name: 'go-jump-rtl-symbolic',                                category: 'Actions' },
    { name: 'go-jump-symbolic',                                    category: 'Actions' },
    { name: 'go-last-symbolic',                                    category: 'Actions' },
    { name: 'go-next-symbolic',                                    category: 'Actions' },
    { name: 'go-previous-symbolic',                                category: 'Actions' },
    { name: 'go-top-symbolic',                                     category: 'Actions' },
    { name: 'go-up-symbolic',                                      category: 'Actions' },
    { name: 'insert-image-symbolic',                               category: 'Actions' },
    { name: 'insert-link-symbolic',                                category: 'Actions' },
    { name: 'insert-object-symbolic',                              category: 'Actions' },
    { name: 'insert-text-symbolic',                                category: 'Actions' },
    { name: 'list-add-symbolic',                                   category: 'Actions' },
    { name: 'list-remove-all-symbolic',                            category: 'Actions' },
    { name: 'list-remove-symbolic',                                category: 'Actions' },
    { name: 'mail-forward-symbolic',                               category: 'Actions' },
    { name: 'mail-mark-important-symbolic',                        category: 'Actions' },
    { name: 'mail-mark-junk-symbolic',                             category: 'Actions' },
    { name: 'mail-mark-notjunk-symbolic',                          category: 'Actions' },
    { name: 'mail-reply-all-rtl-symbolic',                         category: 'Actions' },
    { name: 'mail-reply-all-symbolic',                             category: 'Actions' },
    { name: 'mail-reply-sender-symbolic',                          category: 'Actions' },
    { name: 'mail-send-receive-symbolic',                          category: 'Actions' },
    { name: 'mail-send-symbolic',                                  category: 'Actions' },
    { name: 'media-eject-symbolic',                                category: 'Actions' },
    { name: 'media-playback-pause-symbolic',                       category: 'Actions' },
    { name: 'media-playback-start-symbolic',                       category: 'Actions' },
    { name: 'media-playback-stop-symbolic',                        category: 'Actions' },
    { name: 'media-playlist-consecutive-symbolic',                 category: 'Actions' },
    { name: 'media-playlist-repeat-song-symbolic',                 category: 'Actions' },
    { name: 'media-playlist-repeat-symbolic',                      category: 'Actions' },
    { name: 'media-playlist-shuffle-symbolic',                     category: 'Actions' },
    { name: 'media-record-symbolic',                               category: 'Actions' },
    { name: 'media-seek-backward-symbolic',                        category: 'Actions' },
    { name: 'media-seek-forward-symbolic',                         category: 'Actions' },
    { name: 'media-skip-backward-symbolic',                        category: 'Actions' },
    { name: 'media-skip-forward-symbolic',                         category: 'Actions' },
    { name: 'non-starred-symbolic',                                category: 'Actions' },
    { name: 'object-flip-horizontal-symbolic',                     category: 'Actions' },
    { name: 'object-flip-vertical-symbolic',                       category: 'Actions' },
    { name: 'object-rotate-left-symbolic',                         category: 'Actions' },
    { name: 'object-rotate-right-symbolic',                        category: 'Actions' },
    { name: 'object-select-symbolic',                              category: 'Actions' },
    { name: 'open-menu-symbolic',                                  category: 'Actions' },
    { name: 'pan-down-symbolic',                                   category: 'Actions' },
    { name: 'pan-end-symbolic',                                    category: 'Actions' },
    { name: 'pan-start-symbolic',                                  category: 'Actions' },
    { name: 'pan-up-symbolic',                                     category: 'Actions' },
    { name: 'process-stop-symbolic',                               category: 'Actions' },
    { name: 'rotation-allowed-symbolic',                           category: 'Actions' },
    { name: 'rotation-locked-symbolic',                            category: 'Actions' },
    { name: 'selection-end-symbolic',                              category: 'Actions' },
    { name: 'selection-mode-symbolic',                             category: 'Actions' },
    { name: 'selection-start-symbolic',                            category: 'Actions' },
    { name: 'semi-starred-rtl-symbolic',                           category: 'Actions' },
    { name: 'semi-starred-symbolic',                               category: 'Actions' },
    { name: 'send-to-symbolic',                                    category: 'Actions' },
    { name: 'sidebar-show-right-symbolic',                         category: 'Actions' },
    { name: 'sidebar-show-symbolic',                               category: 'Actions' },
    { name: 'star-new-symbolic',                                   category: 'Actions' },
    { name: 'starred-symbolic',                                    category: 'Actions' },
    { name: 'tab-new-symbolic',                                    category: 'Actions' },
    { name: 'user-bookmarks-symbolic',                             category: 'Actions' },
    { name: 'value-decrease-symbolic',                             category: 'Actions' },
    { name: 'value-increase-symbolic',                             category: 'Actions' },
    { name: 'view-app-grid-symbolic',                              category: 'Actions' },
    { name: 'view-conceal-symbolic',                               category: 'Actions' },
    { name: 'view-continuous-symbolic',                            category: 'Actions' },
    { name: 'view-dual-symbolic',                                  category: 'Actions' },
    { name: 'view-fullscreen-symbolic',                            category: 'Actions' },
    { name: 'view-grid-symbolic',                                  category: 'Actions' },
    { name: 'view-list-bullet-rtl-symbolic',                       category: 'Actions' },
    { name: 'view-list-bullet-symbolic',                           category: 'Actions' },
    { name: 'view-list-ordered-rtl-symbolic',                      category: 'Actions' },
    { name: 'view-list-ordered-symbolic',                          category: 'Actions' },
    { name: 'view-list-rtl-symbolic',                              category: 'Actions' },
    { name: 'view-list-symbolic',                                  category: 'Actions' },
    { name: 'view-mirror-symbolic',                                category: 'Actions' },
    { name: 'view-more-horizontal-symbolic',                       category: 'Actions' },
    { name: 'view-more-symbolic',                                  category: 'Actions' },
    { name: 'view-paged-rtl-symbolic',                             category: 'Actions' },
    { name: 'view-paged-symbolic',                                 category: 'Actions' },
    { name: 'view-pin-symbolic',                                   category: 'Actions' },
    { name: 'view-refresh-symbolic',                               category: 'Actions' },
    { name: 'view-restore-symbolic',                               category: 'Actions' },
    { name: 'view-reveal-symbolic',                                category: 'Actions' },
    { name: 'view-sort-ascending-rtl-symbolic',                    category: 'Actions' },
    { name: 'view-sort-ascending-symbolic',                        category: 'Actions' },
    { name: 'view-sort-descending-rtl-symbolic',                   category: 'Actions' },
    { name: 'view-sort-descending-symbolic',                       category: 'Actions' },
    { name: 'view-wrapped-rtl-symbolic',                           category: 'Actions' },
    { name: 'view-wrapped-symbolic',                               category: 'Actions' },
    { name: 'window-close-symbolic',                               category: 'Actions' },
    { name: 'window-maximize-symbolic',                            category: 'Actions' },
    { name: 'window-minimize-symbolic',                            category: 'Actions' },
    { name: 'window-new-symbolic',                                 category: 'Actions' },
    { name: 'window-restore-symbolic',                             category: 'Actions' },
    { name: 'x-office-document-symbolic',                          category: 'Actions' },
    { name: 'zoom-fit-best-symbolic',                              category: 'Actions' },
    { name: 'zoom-in-symbolic',                                    category: 'Actions' },
    { name: 'zoom-original-symbolic',                              category: 'Actions' },
    { name: 'zoom-out-symbolic',                                   category: 'Actions' },

    { name: 'accessories-calculator-symbolic',                     category: 'Apps' },
    { name: 'accessories-character-map-symbolic',                  category: 'Apps' },
    { name: 'accessories-dictionary-symbolic',                     category: 'Apps' },
    { name: 'accessories-text-editor-symbolic',                    category: 'Apps' },
    { name: 'application-x-executable-symbolic',                   category: 'Apps' },
    { name: 'applications-engineering-symbolic',                   category: 'Apps' },
    { name: 'applications-games-symbolic',                         category: 'Apps' },
    { name: 'applications-graphics-symbolic',                      category: 'Apps' },
    { name: 'applications-multimedia-symbolic',                    category: 'Apps' },
    { name: 'applications-science-symbolic',                       category: 'Apps' },
    { name: 'applications-system-symbolic',                        category: 'Apps' },
    { name: 'applications-utilities-symbolic',                     category: 'Apps' },
    { name: 'help-browser-symbolic',                               category: 'Apps' },
    { name: 'system-file-manager-symbolic',                        category: 'Apps' },
    { name: 'text-editor-symbolic',                                category: 'Apps' },
    { name: 'utilities-terminal-symbolic',                         category: 'Apps' },
    { name: 'web-browser-symbolic',                                category: 'Apps' },

    { name: 'audio-volume-high-rtl-symbolic',                      category: 'Audio & Display' },
    { name: 'audio-volume-high-symbolic',                          category: 'Audio & Display' },
    { name: 'audio-volume-low-rtl-symbolic',                       category: 'Audio & Display' },
    { name: 'audio-volume-low-symbolic',                           category: 'Audio & Display' },
    { name: 'audio-volume-medium-rtl-symbolic',                    category: 'Audio & Display' },
    { name: 'audio-volume-medium-symbolic',                        category: 'Audio & Display' },
    { name: 'audio-volume-muted-rtl-symbolic',                     category: 'Audio & Display' },
    { name: 'audio-volume-muted-symbolic',                         category: 'Audio & Display' },
    { name: 'audio-volume-overamplified-rtl-symbolic',             category: 'Audio & Display' },
    { name: 'audio-volume-overamplified-symbolic',                 category: 'Audio & Display' },
    { name: 'display-brightness-symbolic',                         category: 'Audio & Display' },
    { name: 'keyboard-brightness-symbolic',                        category: 'Audio & Display' },

    { name: 'audio-card-symbolic',                                 category: 'Devices' },
    { name: 'audio-headphones-symbolic',                           category: 'Devices' },
    { name: 'audio-headset-symbolic',                              category: 'Devices' },
    { name: 'audio-input-microphone-symbolic',                     category: 'Devices' },
    { name: 'audio-speakers-rtl-symbolic',                         category: 'Devices' },
    { name: 'audio-speakers-symbolic',                             category: 'Devices' },
    { name: 'camera-disabled-symbolic',                            category: 'Devices' },
    { name: 'camera-hardware-disabled-symbolic',                   category: 'Devices' },
    { name: 'camera-photo-symbolic',                               category: 'Devices' },
    { name: 'camera-switch-symbolic',                              category: 'Devices' },
    { name: 'camera-video-symbolic',                               category: 'Devices' },
    { name: 'camera-web-symbolic',                                 category: 'Devices' },
    { name: 'computer-apple-ipad-symbolic',                        category: 'Devices' },
    { name: 'computer-fail-symbolic',                              category: 'Devices' },
    { name: 'computer-symbolic',                                   category: 'Devices' },
    { name: 'drive-harddisk-ieee1394-symbolic',                    category: 'Devices' },
    { name: 'drive-harddisk-solidstate-symbolic',                  category: 'Devices' },
    { name: 'drive-harddisk-symbolic',                             category: 'Devices' },
    { name: 'drive-harddisk-system-symbolic',                      category: 'Devices' },
    { name: 'drive-harddisk-usb-symbolic',                         category: 'Devices' },
    { name: 'drive-multidisk-symbolic',                            category: 'Devices' },
    { name: 'drive-optical-symbolic',                              category: 'Devices' },
    { name: 'drive-removable-media-symbolic',                      category: 'Devices' },
    { name: 'input-dialpad-symbolic',                              category: 'Devices' },
    { name: 'input-gaming-symbolic',                               category: 'Devices' },
    { name: 'input-keyboard-symbolic',                             category: 'Devices' },
    { name: 'input-mouse-symbolic',                                category: 'Devices' },
    { name: 'input-tablet-symbolic',                               category: 'Devices' },
    { name: 'input-touchpad-symbolic',                             category: 'Devices' },
    { name: 'media-flash-symbolic',                                category: 'Devices' },
    { name: 'media-floppy-symbolic',                               category: 'Devices' },
    { name: 'media-optical-bd-symbolic',                           category: 'Devices' },
    { name: 'media-optical-cd-audio-symbolic',                     category: 'Devices' },
    { name: 'media-optical-cd-symbolic',                           category: 'Devices' },
    { name: 'media-optical-dvd-symbolic',                          category: 'Devices' },
    { name: 'media-optical-symbolic',                              category: 'Devices' },
    { name: 'media-removable-symbolic',                            category: 'Devices' },
    { name: 'media-tape-symbolic',                                 category: 'Devices' },
    { name: 'media-zip-symbolic',                                  category: 'Devices' },
    { name: 'microphone-disabled-symbolic',                        category: 'Devices' },
    { name: 'microphone-hardware-disabled-symbolic',               category: 'Devices' },
    { name: 'microphone-sensitivity-high-symbolic',                category: 'Devices' },
    { name: 'microphone-sensitivity-low-symbolic',                 category: 'Devices' },
    { name: 'microphone-sensitivity-medium-symbolic',              category: 'Devices' },
    { name: 'microphone-sensitivity-muted-symbolic',               category: 'Devices' },
    { name: 'modem-symbolic',                                      category: 'Devices' },
    { name: 'multimedia-player-apple-ipod-touch-symbolic',         category: 'Devices' },
    { name: 'multimedia-player-symbolic',                          category: 'Devices' },
    { name: 'network-server-symbolic',                             category: 'Devices' },
    { name: 'network-workgroup-symbolic',                          category: 'Devices' },
    { name: 'pda-symbolic',                                        category: 'Devices' },
    { name: 'phone-apple-iphone-symbolic',                         category: 'Devices' },
    { name: 'phone-old-symbolic',                                  category: 'Devices' },
    { name: 'phone-symbolic',                                      category: 'Devices' },
    { name: 'printer-error-symbolic',                              category: 'Devices' },
    { name: 'printer-network-symbolic',                            category: 'Devices' },
    { name: 'printer-printing-symbolic',                           category: 'Devices' },
    { name: 'printer-symbolic',                                    category: 'Devices' },
    { name: 'printer-warning-symbolic',                            category: 'Devices' },
    { name: 'scanner-symbolic',                                    category: 'Devices' },
    { name: 'tablet-symbolic',                                     category: 'Devices' },
    { name: 'thunderbolt-acquiring-symbolic',                      category: 'Devices' },
    { name: 'thunderbolt-symbolic',                                category: 'Devices' },
    { name: 'tv-symbolic',                                         category: 'Devices' },
    { name: 'uninterruptible-power-supply-symbolic',               category: 'Devices' },
    { name: 'video-display-symbolic',                              category: 'Devices' },

    { name: 'emoji-activities-symbolic',                           category: 'Emoji Icons' },
    { name: 'emoji-body-symbolic',                                 category: 'Emoji Icons' },
    { name: 'emoji-flags-symbolic',                                category: 'Emoji Icons' },
    { name: 'emoji-food-symbolic',                                 category: 'Emoji Icons' },
    { name: 'emoji-nature-symbolic',                               category: 'Emoji Icons' },
    { name: 'emoji-objects-symbolic',                              category: 'Emoji Icons' },
    { name: 'emoji-people-symbolic',                               category: 'Emoji Icons' },
    { name: 'emoji-recent-symbolic',                               category: 'Emoji Icons' },
    { name: 'emoji-symbols-symbolic',                              category: 'Emoji Icons' },
    { name: 'emoji-travel-symbolic',                               category: 'Emoji Icons' },

    { name: 'emote-love-symbolic',                                 category: 'Emotes' },
    { name: 'face-angel-symbolic',                                 category: 'Emotes' },
    { name: 'face-angry-symbolic',                                 category: 'Emotes' },
    { name: 'face-confused-symbolic',                              category: 'Emotes' },
    { name: 'face-cool-symbolic',                                  category: 'Emotes' },
    { name: 'face-crying-symbolic',                                category: 'Emotes' },
    { name: 'face-devilish-symbolic',                              category: 'Emotes' },
    { name: 'face-embarrassed-symbolic',                           category: 'Emotes' },
    { name: 'face-glasses-symbolic',                               category: 'Emotes' },
    { name: 'face-kiss-symbolic',                                  category: 'Emotes' },
    { name: 'face-laugh-symbolic',                                 category: 'Emotes' },
    { name: 'face-monkey-symbolic',                                category: 'Emotes' },
    { name: 'face-plain-symbolic',                                 category: 'Emotes' },
    { name: 'face-raspberry-symbolic',                             category: 'Emotes' },
    { name: 'face-sad-symbolic',                                   category: 'Emotes' },
    { name: 'face-shutmouth-symbolic',                             category: 'Emotes' },
    { name: 'face-sick-symbolic',                                  category: 'Emotes' },
    { name: 'face-smile-big-symbolic',                             category: 'Emotes' },
    { name: 'face-smile-symbolic',                                 category: 'Emotes' },
    { name: 'face-smirk-symbolic',                                 category: 'Emotes' },
    { name: 'face-surprise-symbolic',                              category: 'Emotes' },
    { name: 'face-tired-symbolic',                                 category: 'Emotes' },
    { name: 'face-uncertain-symbolic',                             category: 'Emotes' },
    { name: 'face-wink-symbolic',                                  category: 'Emotes' },
    { name: 'face-worried-symbolic',                               category: 'Emotes' },
    { name: 'face-yawn-symbolic',                                  category: 'Emotes' },

    { name: 'application-rss+xml-symbolic',                        category: 'Files' },
    { name: 'application-x-addon-symbolic',                        category: 'Files' },
    { name: 'application-x-appliance-symbolic',                    category: 'Files' },
    { name: 'application-x-firmware-symbolic',                     category: 'Files' },
    { name: 'application-x-sharedlib-symbolic',                    category: 'Files' },
    { name: 'audio-x-generic-symbolic',                            category: 'Files' },
    { name: 'folder-documents-symbolic',                           category: 'Files' },
    { name: 'folder-download-symbolic',                            category: 'Files' },
    { name: 'folder-drag-accept-symbolic',                         category: 'Files' },
    { name: 'folder-drag-accept-symbolic',                         category: 'Files' },
    { name: 'folder-music-symbolic',                               category: 'Files' },
    { name: 'folder-new-symbolic',                                 category: 'Files' },
    { name: 'folder-open-symbolic',                                category: 'Files' },
    { name: 'folder-pictures-symbolic',                            category: 'Files' },
    { name: 'folder-publicshare-symbolic',                         category: 'Files' },
    { name: 'folder-remote-symbolic',                              category: 'Files' },
    { name: 'folder-saved-search-symbolic',                        category: 'Files' },
    { name: 'folder-symbolic',                                     category: 'Files' },
    { name: 'folder-templates-symbolic',                           category: 'Files' },
    { name: 'folder-videos-symbolic',                              category: 'Files' },
    { name: 'folder-visiting-symbolic',                            category: 'Files' },
    { name: 'font-x-generic-symbolic',                             category: 'Files' },
    { name: 'image-x-generic-symbolic',                            category: 'Files' },
    { name: 'inode-directory-symbolic',                            category: 'Files' },
    { name: 'package-x-generic-symbolic',                          category: 'Files' },
    { name: 'text-x-generic-symbolic',                             category: 'Files' },
    { name: 'video-x-generic-symbolic',                            category: 'Files' },
    { name: 'x-office-address-book-symbolic',                      category: 'Files' },
    { name: 'x-office-calendar-symbolic',                          category: 'Files' },
    { name: 'x-office-drawing-symbolic',                           category: 'Files' },
    { name: 'x-office-presentation-symbolic',                      category: 'Files' },
    { name: 'x-office-spreadsheet-symbolic',                       category: 'Files' },

    { name: 'airplane-mode-symbolic',                              category: 'Misc' },
    { name: 'alarm-symbolic',                                      category: 'Misc' },
    { name: 'applets-screenshooter-symbolic',                      category: 'Misc' },
    { name: 'application-certificate-symbolic',                    category: 'Misc' },
    { name: 'application-exit-rtl-symbolic',                       category: 'Misc' },
    { name: 'application-exit-symbolic',                           category: 'Misc' },
    { name: 'chat-message-new-symbolic',                           category: 'Misc' },
    { name: 'checkbox-checked-symbolic',                           category: 'Misc' },
    { name: 'checkbox-mixed-symbolic',                             category: 'Misc' },
    { name: 'checkbox-symbolic',                                   category: 'Misc' },
    { name: 'color-select-symbolic',                               category: 'Misc' },
    { name: 'colorimeter-colorhug-symbolic',                       category: 'Misc' },
    { name: 'display-projector-symbolic',                          category: 'Misc' },
    { name: 'find-location-symbolic',                              category: 'Misc' },
    { name: 'focus-legacy-systray-symbolic',                       category: 'Misc' },
    { name: 'focus-top-bar-symbolic',                              category: 'Misc' },
    { name: 'focus-windows-symbolic',                              category: 'Misc' },
    { name: 'font-select-symbolic',                                category: 'Misc' },
    { name: 'goa-panel-symbolic',                                  category: 'Misc' },
    { name: 'help-about-symbolic',                                 category: 'Misc' },
    { name: 'help-contents-symbolic',                              category: 'Misc' },
    { name: 'help-contents-symbolic',                              category: 'Misc' },
    { name: 'help-faq-symbolic',                                   category: 'Misc' },
    { name: 'list-drag-handle-symbolic',                           category: 'Misc' },
    { name: 'location-services-active-symbolic',                   category: 'Misc' },
    { name: 'location-services-disabled-symbolic',                 category: 'Misc' },
    { name: 'mail-attachment-symbolic',                            category: 'Misc' },
    { name: 'mail-message-new-symbolic',                           category: 'Misc' },
    { name: 'mail-read-symbolic',                                  category: 'Misc' },
    { name: 'mail-replied-rtl-symbolic',                           category: 'Misc' },
    { name: 'mail-replied-symbolic',                               category: 'Misc' },
    { name: 'mail-unread-symbolic',                                category: 'Misc' },
    { name: 'mark-location-symbolic',                              category: 'Misc' },
    { name: 'media-view-subtitles-symbolic',                       category: 'Misc' },
    { name: 'multimedia-volume-control-symbolic',                  category: 'Misc' },
    { name: 'orientation-landscape-inverse-symbolic',              category: 'Misc' },
    { name: 'orientation-landscape-symbolic',                      category: 'Misc' },
    { name: 'orientation-portrait-left-symbolic',                  category: 'Misc' },
    { name: 'orientation-portrait-right-symbolic',                 category: 'Misc' },
    { name: 'radio-checked-symbolic',                              category: 'Misc' },
    { name: 'radio-mixed-symbolic',                                category: 'Misc' },
    { name: 'radio-symbolic',                                      category: 'Misc' },
    { name: 'screen-shared-symbolic',                              category: 'Misc' },
    { name: 'start-here-symbolic',                                 category: 'Misc' },
    { name: 'system-help-symbolic',                                category: 'Misc' },
    { name: 'system-search-symbolic',                              category: 'Misc' },
    { name: 'system-software-install-symbolic',                    category: 'Misc' },
    { name: 'touch-disabled-symbolic',                             category: 'Misc' },
    { name: 'touchpad-disabled-symbolic',                          category: 'Misc' },
    { name: 'video-joined-displays-symbolic',                      category: 'Misc' },
    { name: 'video-single-display-symbolic',                       category: 'Misc' },

    { name: 'bluetooth-acquiring-symbolic',                        category: 'Network' },
    { name: 'bluetooth-active-symbolic',                           category: 'Network' },
    { name: 'bluetooth-disabled-symbolic',                         category: 'Network' },
    { name: 'bluetooth-disconnected-symbolic',                     category: 'Network' },
    { name: 'bluetooth-hardware-disabled-symbolic',                category: 'Network' },
    { name: 'bluetooth-symbolic',                                  category: 'Network' },
    { name: 'network-cellular-2g-symbolic',                        category: 'Network' },
    { name: 'network-cellular-3g-symbolic',                        category: 'Network' },
    { name: 'network-cellular-4g-symbolic',                        category: 'Network' },
    { name: 'network-cellular-5g-symbolic',                        category: 'Network' },
    { name: 'network-cellular-acquiring-rtl-symbolic',             category: 'Network' },
    { name: 'network-cellular-acquiring-symbolic',                 category: 'Network' },
    { name: 'network-cellular-connected-symbolic',                 category: 'Network' },
    { name: 'network-cellular-disabled-rtl-symbolic',              category: 'Network' },
    { name: 'network-cellular-disabled-symbolic',                  category: 'Network' },
    { name: 'network-cellular-edge-symbolic',                      category: 'Network' },
    { name: 'network-cellular-gprs-symbolic',                      category: 'Network' },
    { name: 'network-cellular-hardware-disabled-rtl-symbolic',     category: 'Network' },
    { name: 'network-cellular-hardware-disabled-symbolic',         category: 'Network' },
    { name: 'network-cellular-hspa-symbolic',                      category: 'Network' },
    { name: 'network-cellular-no-route-rtl-symbolic',              category: 'Network' },
    { name: 'network-cellular-no-route-symbolic',                  category: 'Network' },
    { name: 'network-cellular-offline-rtl-symbolic',               category: 'Network' },
    { name: 'network-cellular-offline-symbolic',                   category: 'Network' },
    { name: 'network-cellular-signal-excellent-rtl-symbolic',      category: 'Network' },
    { name: 'network-cellular-signal-excellent-symbolic',          category: 'Network' },
    { name: 'network-cellular-signal-good-rtl-symbolic',           category: 'Network' },
    { name: 'network-cellular-signal-good-symbolic',               category: 'Network' },
    { name: 'network-cellular-signal-none-rtl-symbolic',           category: 'Network' },
    { name: 'network-cellular-signal-none-symbolic',               category: 'Network' },
    { name: 'network-cellular-signal-ok-rtl-symbolic',             category: 'Network' },
    { name: 'network-cellular-signal-ok-symbolic',                 category: 'Network' },
    { name: 'network-cellular-signal-weak-rtl-symbolic',           category: 'Network' },
    { name: 'network-cellular-signal-weak-symbolic',               category: 'Network' },
    { name: 'network-cellular-symbolic',                           category: 'Network' },
    { name: 'network-error-symbolic',                              category: 'Network' },
    { name: 'network-idle-symbolic',                               category: 'Network' },
    { name: 'network-no-route-symbolic',                           category: 'Network' },
    { name: 'network-offline-symbolic',                            category: 'Network' },
    { name: 'network-receive-symbolic',                            category: 'Network' },
    { name: 'network-transmit-receive-symbolic',                   category: 'Network' },
    { name: 'network-transmit-symbolic',                           category: 'Network' },
    { name: 'network-vpn-acquiring-symbolic',                      category: 'Network' },
    { name: 'network-vpn-disabled-symbolic',                       category: 'Network' },
    { name: 'network-vpn-disconnected-symbolic',                   category: 'Network' },
    { name: 'network-vpn-no-route-symbolic',                       category: 'Network' },
    { name: 'network-vpn-symbolic',                                category: 'Network' },
    { name: 'network-wired-acquiring-symbolic',                    category: 'Network' },
    { name: 'network-wired-disconnected-symbolic',                 category: 'Network' },
    { name: 'network-wired-no-route-symbolic',                     category: 'Network' },
    { name: 'network-wired-symbolic',                              category: 'Network' },
    { name: 'network-wireless-acquiring-symbolic',                 category: 'Network' },
    { name: 'network-wireless-connected-symbolic',                 category: 'Network' },
    { name: 'network-wireless-disabled-symbolic',                  category: 'Network' },
    { name: 'network-wireless-encrypted-symbolic',                 category: 'Network' },
    { name: 'network-wireless-hardware-disabled-symbolic',         category: 'Network' },
    { name: 'network-wireless-hotspot-symbolic',                   category: 'Network' },
    { name: 'network-wireless-no-route-symbolic',                  category: 'Network' },
    { name: 'network-wireless-offline-symbolic',                   category: 'Network' },
    { name: 'network-wireless-signal-excellent-symbolic',          category: 'Network' },
    { name: 'network-wireless-signal-good-symbolic',               category: 'Network' },
    { name: 'network-wireless-signal-none-symbolic',               category: 'Network' },
    { name: 'network-wireless-signal-ok-symbolic',                 category: 'Network' },
    { name: 'network-wireless-signal-weak-symbolic',               category: 'Network' },
    { name: 'network-wireless-symbolic',                           category: 'Network' },

    { name: 'address-book-new-symbolic',                           category: 'People' },
    { name: 'avatar-default-symbolic',                             category: 'People' },
    { name: 'contact-new-symbolic',                                category: 'People' },
    { name: 'system-switch-user-rtl-symbolic',                     category: 'People' },
    { name: 'system-switch-user-symbolic',                         category: 'People' },
    { name: 'system-users-symbolic',                               category: 'People' },
    { name: 'user-available-symbolic',                             category: 'People' },
    { name: 'user-away-symbolic',                                  category: 'People' },
    { name: 'user-busy-symbolic',                                  category: 'People' },
    { name: 'user-desktop-symbolic',                               category: 'People' },
    { name: 'user-home-symbolic',                                  category: 'People' },
    { name: 'user-idle-symbolic',                                  category: 'People' },
    { name: 'user-info-symbolic',                                  category: 'People' },
    { name: 'user-invisible-symbolic',                             category: 'People' },
    { name: 'user-not-tracked-symbolic',                           category: 'People' },
    { name: 'user-offline-symbolic',                               category: 'People' },
    { name: 'user-status-pending-symbolic',                        category: 'People' },
    { name: 'user-trash-full-symbolic',                            category: 'People' },
    { name: 'user-trash-symbolic',                                 category: 'People' },

    { name: 'ac-adapter-symbolic',                                 category: 'Power' },
    { name: 'battery-action-symbolic',                             category: 'Power' },
    { name: 'battery-caution-charging-symbolic',                   category: 'Power' },
    { name: 'battery-caution-symbolic',                            category: 'Power' },
    { name: 'battery-empty-charging-symbolic',                     category: 'Power' },
    { name: 'battery-empty-symbolic',                              category: 'Power' },
    { name: 'battery-full-charged-symbolic',                       category: 'Power' },
    { name: 'battery-full-charging-symbolic',                      category: 'Power' },
    { name: 'battery-full-symbolic',                               category: 'Power' },
    { name: 'battery-good-charging-symbolic',                      category: 'Power' },
    { name: 'battery-good-symbolic',                               category: 'Power' },
    { name: 'battery-level-0-charging-symbolic',                   category: 'Power' },
    { name: 'battery-level-0-symbolic',                            category: 'Power' },
    { name: 'battery-level-10-charging-symbolic',                  category: 'Power' },
    { name: 'battery-level-10-symbolic',                           category: 'Power' },
    { name: 'battery-level-100-charged-symbolic',                  category: 'Power' },
    { name: 'battery-level-100-symbolic',                          category: 'Power' },
    { name: 'battery-level-20-charging-symbolic',                  category: 'Power' },
    { name: 'battery-level-20-symbolic',                           category: 'Power' },
    { name: 'battery-level-30-charging-symbolic',                  category: 'Power' },
    { name: 'battery-level-30-symbolic',                           category: 'Power' },
    { name: 'battery-level-40-charging-symbolic',                  category: 'Power' },
    { name: 'battery-level-40-symbolic',                           category: 'Power' },
    { name: 'battery-level-50-charging-symbolic',                  category: 'Power' },
    { name: 'battery-level-50-symbolic',                           category: 'Power' },
    { name: 'battery-level-60-charging-symbolic',                  category: 'Power' },
    { name: 'battery-level-60-symbolic',                           category: 'Power' },
    { name: 'battery-level-70-charging-symbolic',                  category: 'Power' },
    { name: 'battery-level-70-symbolic',                           category: 'Power' },
    { name: 'battery-level-80-charging-symbolic',                  category: 'Power' },
    { name: 'battery-level-80-symbolic',                           category: 'Power' },
    { name: 'battery-level-90-charging-symbolic',                  category: 'Power' },
    { name: 'battery-level-90-symbolic',                           category: 'Power' },
    { name: 'battery-low-charging-symbolic',                       category: 'Power' },
    { name: 'battery-low-symbolic',                                category: 'Power' },
    { name: 'battery-missing-symbolic',                            category: 'Power' },
    { name: 'battery-symbolic',                                    category: 'Power' },
    { name: 'gnome-power-manager-symbolic',                        category: 'Power' },
    { name: 'power-profile-balanced-rtl-symbolic',                 category: 'Power' },
    { name: 'power-profile-balanced-symbolic',                     category: 'Power' },
    { name: 'power-profile-performance-rtl-symbolic',              category: 'Power' },
    { name: 'power-profile-performance-symbolic',                  category: 'Power' },
    { name: 'power-profile-power-saver-rtl-symbolic',              category: 'Power' },
    { name: 'power-profile-power-saver-symbolic',                  category: 'Power' },
    { name: 'system-log-out-rtl-symbolic',                         category: 'Power' },
    { name: 'system-log-out-symbolic',                             category: 'Power' },
    { name: 'system-reboot-symbolic',                              category: 'Power' },
    { name: 'system-run-symbolic',                                 category: 'Power' },
    { name: 'system-shutdown-symbolic',                            category: 'Power' },

    { name: 'auth-face-symbolic',                                  category: 'Security' },
    { name: 'auth-fingerprint-symbolic',                           category: 'Security' },
    { name: 'auth-sim-locked-symbolic',                            category: 'Security' },
    { name: 'auth-sim-missing-symbolic',                           category: 'Security' },
    { name: 'auth-sim-symbolic',                                   category: 'Security' },
    { name: 'auth-smartcard-symbolic',                             category: 'Security' },
    { name: 'channel-insecure-symbolic',                           category: 'Security' },
    { name: 'channel-secure-symbolic',                             category: 'Security' },
    { name: 'security-high-symbolic',                              category: 'Security' },
    { name: 'security-low-symbolic',                               category: 'Security' },
    { name: 'security-medium-rtl-symbolic',                        category: 'Security' },
    { name: 'security-medium-symbolic',                            category: 'Security' },
    { name: 'system-lock-screen-symbolic',                         category: 'Security' },

    { name: 'preferences-color-symbolic',                          category: 'Settings' },
    { name: 'preferences-desktop-accessibility-symbolic',          category: 'Settings' },
    { name: 'preferences-desktop-appearance-symbolic',             category: 'Settings' },
    { name: 'preferences-desktop-apps-symbolic',                   category: 'Settings' },
    { name: 'preferences-desktop-display-symbolic',                category: 'Settings' },
    { name: 'preferences-desktop-font-symbolic',                   category: 'Settings' },
    { name: 'preferences-desktop-keyboard-shortcuts-symbolic',     category: 'Settings' },
    { name: 'preferences-desktop-keyboard-symbolic',               category: 'Settings' },
    { name: 'preferences-desktop-locale-symbolic',                 category: 'Settings' },
    { name: 'preferences-desktop-multitasking-symbolic',           category: 'Settings' },
    { name: 'preferences-desktop-remote-desktop-symbolic',         category: 'Settings' },
    { name: 'preferences-desktop-screensaver-symbolic',            category: 'Settings' },
    { name: 'preferences-desktop-wallpaper-symbolic',              category: 'Settings' },
    { name: 'preferences-other-symbolic',                          category: 'Settings' },
    { name: 'preferences-system-details-symbolic',                 category: 'Settings' },
    { name: 'preferences-system-devices-symbolic',                 category: 'Settings' },
    { name: 'preferences-system-network-proxy-symbolic',           category: 'Settings' },
    { name: 'preferences-system-network-symbolic',                 category: 'Settings' },
    { name: 'preferences-system-notifications-symbolic',           category: 'Settings' },
    { name: 'preferences-system-parental-controls-symbolic',       category: 'Settings' },
    { name: 'preferences-system-privacy-symbolic',                 category: 'Settings' },
    { name: 'preferences-system-search-symbolic',                  category: 'Settings' },
    { name: 'preferences-system-sharing-symbolic',                 category: 'Settings' },
    { name: 'preferences-system-symbolic',                         category: 'Settings' },
    { name: 'preferences-system-time-symbolic',                    category: 'Settings' },

    { name: 'action-unavailable-symbolic',                         category: 'Status' },
    { name: 'appointment-missed-symbolic',                         category: 'Status' },
    { name: 'appointment-new-symbolic',                            category: 'Status' },
    { name: 'appointment-soon-symbolic',                           category: 'Status' },
    { name: 'changes-allow-symbolic',                              category: 'Status' },
    { name: 'changes-prevent-symbolic',                            category: 'Status' },
    { name: 'content-loading-symbolic',                            category: 'Status' },
    { name: 'dialog-error-symbolic',                               category: 'Status' },
    { name: 'dialog-information-symbolic',                         category: 'Status' },
    { name: 'dialog-password-symbolic',                            category: 'Status' },
    { name: 'dialog-question-symbolic',                            category: 'Status' },
    { name: 'dialog-warning-symbolic',                             category: 'Status' },
    { name: 'emblem-default-symbolic',                             category: 'Status' },
    { name: 'emblem-documents-symbolic',                           category: 'Status' },
    { name: 'emblem-favorite-symbolic',                            category: 'Status' },
    { name: 'emblem-important-symbolic',                           category: 'Status' },
    { name: 'emblem-music-symbolic',                               category: 'Status' },
    { name: 'emblem-ok-symbolic',                                  category: 'Status' },
    { name: 'emblem-photos-symbolic',                              category: 'Status' },
    { name: 'emblem-shared-symbolic',                              category: 'Status' },
    { name: 'emblem-synchronizing-symbolic',                       category: 'Status' },
    { name: 'emblem-system-symbolic',                              category: 'Status' },
    { name: 'emblem-videos-symbolic',                              category: 'Status' },
    { name: 'error-correct-symbolic',                              category: 'Status' },
    { name: 'image-loading-symbolic',                              category: 'Status' },
    { name: 'image-missing-symbolic',                              category: 'Status' },
    { name: 'notifications-disabled-symbolic',                     category: 'Status' },
    { name: 'software-update-available-symbolic',                  category: 'Status' },
    { name: 'software-update-urgent-symbolic',                     category: 'Status' },
    { name: 'task-due-symbolic',                                   category: 'Status' },
    { name: 'task-past-due-symbolic',                              category: 'Status' },

    { name: 'format-indent-less-rtl-symbolic',                     category: 'Text Formatting' },
    { name: 'format-indent-less-symbolic',                         category: 'Text Formatting' },
    { name: 'format-indent-more-rtl-symbolic',                     category: 'Text Formatting' },
    { name: 'format-indent-more-symbolic',                         category: 'Text Formatting' },
    { name: 'format-justify-center-symbolic',                      category: 'Text Formatting' },
    { name: 'format-justify-fill-symbolic',                        category: 'Text Formatting' },
    { name: 'format-justify-left-symbolic',                        category: 'Text Formatting' },
    { name: 'format-justify-right-symbolic',                       category: 'Text Formatting' },
    { name: 'format-text-bold-symbolic',                           category: 'Text Formatting' },
    { name: 'format-text-direction-ltr-symbolic',                  category: 'Text Formatting' },
    { name: 'format-text-direction-rtl-symbolic',                  category: 'Text Formatting' },
    { name: 'format-text-direction-symbolic',                      category: 'Text Formatting' },
    { name: 'format-text-italic-symbolic',                         category: 'Text Formatting' },
    { name: 'format-text-plaintext-symbolic',                      category: 'Text Formatting' },
    { name: 'format-text-rich-symbolic',                           category: 'Text Formatting' },
    { name: 'format-text-strikethrough-symbolic',                  category: 'Text Formatting' },
    { name: 'format-text-underline-symbolic',                      category: 'Text Formatting' },
    { name: 'tools-check-spelling-symbolic',                       category: 'Text Formatting' },

    { name: 'daytime-sunrise-symbolic',                            category: 'Weather' },
    { name: 'daytime-sunset-symbolic',                             category: 'Weather' },
    { name: 'night-light-disabled-symbolic',                       category: 'Weather' },
    { name: 'night-light-symbolic',                                category: 'Weather' },
    { name: 'weather-clear-night-symbolic',                        category: 'Weather' },
    { name: 'weather-clear-symbolic',                              category: 'Weather' },
    { name: 'weather-few-clouds-night-symbolic',                   category: 'Weather' },
    { name: 'weather-few-clouds-symbolic',                         category: 'Weather' },
    { name: 'weather-fog-symbolic',                                category: 'Weather' },
    { name: 'weather-overcast-symbolic',                           category: 'Weather' },
    { name: 'weather-severe-alert-symbolic',                       category: 'Weather' },
    { name: 'weather-showers-scattered-symbolic',                  category: 'Weather' },
    { name: 'weather-showers-symbolic',                            category: 'Weather' },
    { name: 'weather-snow-symbolic',                               category: 'Weather' },
    { name: 'weather-storm-symbolic',                              category: 'Weather' },
    { name: 'weather-tornado-symbolic',                            category: 'Weather' },
    { name: 'weather-windy-symbolic',                              category: 'Weather' },

];

let _currentIconCategory = 'All';

export function getIconCategories() {
    let cats = new Set();
    ICON_CATALOG.forEach(e => { if (e.category) cats.add(e.category); });
    return ['All', ...Array.from(cats)];
}

export function getIconCategory() { return _currentIconCategory; }
export function setIconCategory(cat) { _currentIconCategory = cat; }

export function searchIcons(query) {
    let q = query ? query.toLowerCase().trim() : '';
    let matches = ICON_CATALOG;

    if (_currentIconCategory !== 'All') {
        matches = matches.filter(e => e.category === _currentIconCategory);
    }

    if (q) {
        matches = matches.filter(entry =>
            entry.name.includes(q) || entry.category.toLowerCase().includes(q)
        );
    }

    return matches.slice(0, 200).map(entry => ({
        type: 'icon-browser',
        name: entry.name,
        description: `Category: ${entry.category} • Click to copy name`,
        icon: new Gio.ThemedIcon({ name: entry.name }),
        text: entry.name,
    }));
}